### ISSUE TITLE
update licence for this project. 

### ISSUE THREAD

**Issue by Xeeshuu** [knirirr/BeeCount#22]

**Comment by knirirr** [comment]
Please provide more details - thanks.

**Comment by Xeeshuu** [comment]
Update licence to this REPOSTORY so that we will be able to contribute about this REPOSTORY through different projects.

**Comment by Xeeshuu** [comment]
Is this REPOSTORY contain license?

**Comment by knirirr** [comment]
Do you have anything in particular in mind? I'm not sure whether you mean that you'd like to contribute code to this project or use it elsewhere.

**Comment by knirirr** [comment]
May I ask what project that was?

**Comment by Xeeshuu** [comment]
utopian

**Comment by Xeeshuu** [comment]
Link of what?

**Comment by knirirr** [comment]
A link to whatever web page describes 'utopian', mentioned by you in this comment:

https://github.com/knirirr/BeeCount/issues/22#issuecomment-389209051

It might help make some sense of this very bizarre thread.

**Comment by knirirr** [comment]
Thanks.

**Comment by Xeeshuu** [comment]
So will you update licence?
